CREATE TABLE .DYNAMIC_OBJECTS (
  UNIQUE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
  CLASS varchar2(100) NOT NULL,
  ID varchar2(100) NOT NULL,
  FROM_TIME timestamp NOT NULL,
  TO_TIME timestamp,
  ATTRIBUTE varchar2(100) NOT NULL,
  CONTENT varchar2(2000),
  CONSTRAINT DYNAMIC_OBJECTS_PK PRIMARY KEY (UNIQUE_ID)
);
COMMIT;