/**
 * This file Copyright (c) 2003-2011 Dr. Ralf Hirning
 * All rights reserved.
 *
 *
 * This file is dual-licensed under both the GNU General
 * Public License and an individual license with Dr. Ralf
 * Hirning.
 *
 * This file is distributed in the hope that it will be
 * useful, but AS-IS and WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE, TITLE, or NONINFRINGEMENT.
 * Redistribution, except as permitted by whichever of the GPL
 * or the individual license, is prohibited.
 *
 * 1. For the GPL license (GPL), you can redistribute and/or
 * modify this file under the terms of the GNU General
 * Public License, Version 3, as published by the Free Software
 * Foundation.  You should have received a copy of the GNU
 * General Public License, Version 3 along with this program;
 * if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * 2. For the individual license, this file and the accompanying
 * materials are made available under the terms of the
 * individual license.
 *
 * Any modifications to this file must keep this entire header
 * intact.
 *
 */
package org.mgnl.nicki.editor.catalogs;

import org.mgnl.nicki.core.data.TreeData;
import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.core.objects.DynamicObjectException;
import org.mgnl.nicki.shop.base.objects.CatalogPage;
import org.mgnl.nicki.vaadin.base.components.EnterNameDialog;
import org.mgnl.nicki.vaadin.base.components.EnterNameHandler;
import org.mgnl.nicki.vaadin.base.editor.ClassEditor;
import org.mgnl.nicki.vaadin.base.editor.NickiTreeEditor;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class CatalogPageViewer extends CustomComponent implements ClassEditor {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button deleteAttributeButton;
	@AutoGenerated
	private Button newAttributeButton;
	@AutoGenerated
	private Table attributes;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button deleteCategoryButton;
	@AutoGenerated
	private Button newCategoryButton;
	@AutoGenerated
	private Table categories;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private CatalogPage page;

	public CatalogPageViewer() {
	}

	public void setDynamicObject(NickiTreeEditor nickiEditor,
			TreeData dynamicObject) {
		this.page = (CatalogPage) dynamicObject;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		initCategories();
		initAttributes();

	}

	private void initCategories() {
		categories.setSelectable(true);
		categories.addContainerProperty("category", String.class, null);
		if (page.hasCategories()) {
			for (String value : page.getCategories()) {
				categories.addItem(new Object[] { value }, value);
			}
		}
		newCategoryButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				addEntry(categories);
			}
		});
		deleteCategoryButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				deleteEntry(categories);
			}
		});
	}

	protected void deleteEntry(Table table) {
		if (table.getValue() != null) {
			table.removeItem(table.getValue());
		}
	}

	protected void addEntry(Table table) {
		EnterNameHandler handler = new NewEntryEnterNameHandler(table);
		EnterNameDialog dialog = new EnterNameDialog(
				"nicki.editor.catalogs.entry.new", I18n.getText("nicki.editor.catalogs.entry.new.window.title"));
		dialog.setHandler(handler);
		dialog.setWidth(440, Unit.PIXELS);
		dialog.setHeight(500, Unit.PIXELS);
		dialog.setModal(true);
		UI.getCurrent().addWindow(dialog);
	}

	private void initAttributes() {
		attributes.setSelectable(true);
		attributes.addContainerProperty("attribute", String.class, null);
		if (page.hasAttributes()) {
			for (String value : page.getCategories()) {
				attributes.addItem(new Object[] { value }, value);
			}
		}
		newAttributeButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				addEntry(attributes);
			}
		});
		deleteAttributeButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				deleteEntry(attributes);
			}
		});
	}

	@Override
	public void save() throws DynamicObjectException {
		if (this.page.isNew()) {
			this.page.create();
		} else {
			Notification.show(
					"Object changed: " + this.page.isModified());
			this.page.update();
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		
		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Speichern");
		saveButton.setImmediate(true);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		mainLayout.addComponent(saveButton);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// categories
		categories = new Table();
		categories.setCaption("Kategorien");
		categories.setImmediate(false);
		categories.setWidth("400px");
		categories.setHeight("120px");
		horizontalLayout_1.addComponent(categories);
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		horizontalLayout_1.addComponent(verticalLayout_1);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(true);
		verticalLayout_1.setSpacing(true);
		
		// newCategoryButton
		newCategoryButton = new Button();
		newCategoryButton.setCaption("Neu");
		newCategoryButton.setImmediate(true);
		newCategoryButton.setWidth("-1px");
		newCategoryButton.setHeight("-1px");
		verticalLayout_1.addComponent(newCategoryButton);
		
		// deleteCategoryButton
		deleteCategoryButton = new Button();
		deleteCategoryButton.setCaption("Löschen");
		deleteCategoryButton.setImmediate(true);
		deleteCategoryButton.setWidth("-1px");
		deleteCategoryButton.setHeight("-1px");
		verticalLayout_1.addComponent(deleteCategoryButton);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// attributes
		attributes = new Table();
		attributes.setCaption("Attribute");
		attributes.setImmediate(false);
		attributes.setWidth("400px");
		attributes.setHeight("120px");
		horizontalLayout_2.addComponent(attributes);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_2.addComponent(verticalLayout_2);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// newAttributeButton
		newAttributeButton = new Button();
		newAttributeButton.setCaption("Neu");
		newAttributeButton.setImmediate(true);
		newAttributeButton.setWidth("-1px");
		newAttributeButton.setHeight("-1px");
		verticalLayout_2.addComponent(newAttributeButton);
		
		// deleteAttributeButton
		deleteAttributeButton = new Button();
		deleteAttributeButton.setCaption("Löschen");
		deleteAttributeButton.setImmediate(true);
		deleteAttributeButton.setWidth("-1px");
		deleteAttributeButton.setHeight("-1px");
		verticalLayout_2.addComponent(deleteAttributeButton);
		
		return verticalLayout_2;
	}
}
