CREATE TABLE TEST.ERROR (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  COMMAND char(64) NOT NULL,
  MODIFY_TIME timestamp NOT NULL,
  USER_ID char(64),
  CODE char(64),
  DATA varchar(4000),
  CONSTRAINT ERROR_PK PRIMARY KEY (ID)
)
