CREATE TABLE APP.FILE_STORE (
  ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME varchar(1000) NOT NULL,
  DATA CLOB,
  MODIFY_TIME TIMESTAMP NOT NULL,
  CONSTRAINT FILE_STORE_PK PRIMARY KEY (ID)
);

drop table APP.IDM_CONFIG;