package org.mgnl.nicki.shop.core;

import org.mgnl.nicki.core.helper.DataHelper;
import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.shop.base.inventory.Inventory;
import org.mgnl.nicki.shop.base.inventory.InventoryArticle;
import org.mgnl.nicki.shop.base.objects.Cart;
import org.mgnl.nicki.shop.base.objects.CartEntry;
import org.mgnl.nicki.shop.base.objects.Catalog;
import org.mgnl.nicki.shop.base.objects.CatalogArticle;
import org.mgnl.nicki.shop.base.objects.Cart.CART_STATUS;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class CartViewer extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table cartEntries;
	@AutoGenerated
	private Label recipient;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	private static final long serialVersionUID = 8441664095916322794L;
	private Cart cart;
	private Inventory inventory;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CartViewer(Cart cart) {
		this.cart = cart;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.recipient.setValue(this.cart.getRecipient().getDisplayName());
		fillCartEntries();
	}

	public CartViewer(Inventory inventory) {
		this.inventory = inventory;
		this.cart = inventory.getCart("SHOP", CART_STATUS.NEW);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.recipient.setValue(this.inventory.getPerson().getDisplayName());
		fillCartEntries();
	}

	@SuppressWarnings("unchecked")
	private void fillCartEntries() {

		cartEntries.addContainerProperty("action", String.class, "");
		cartEntries.setColumnWidth("action", 50);
		cartEntries.setColumnHeader("action", "Aktion");
		cartEntries.addContainerProperty("right", String.class, "");
		cartEntries.setColumnWidth("right", -1);
		cartEntries.setColumnHeader("right", "Artikel");
		/*
		cartEntries.addContainerProperty("start", String.class, "");
		cartEntries.setColumnWidth("start", 70);
		cartEntries.setColumnHeader("start", I18n.getText(CatalogArticle.CAPTION_START));
		cartEntries.addContainerProperty("end", String.class, "");
		cartEntries.setColumnWidth("end", 70);
		cartEntries.setColumnHeader("end", I18n.getText(CatalogArticle.CAPTION_END));

		cartEntries.addContainerProperty("attributes", String.class, "");
		cartEntries.setColumnWidth("attributes", 420);
		cartEntries.setColumnHeader("attributes", "attributes");
		*/
		for (CartEntry cartEntry : cart.getCartEntries()) {
			Item item = cartEntries.addItem(cartEntry);
			item.getItemProperty("right").setValue(cartEntry.getDisplayName());
			item.getItemProperty("action").setValue(cartEntry.getAction().toString());
			/*
			if (cartEntry.getStart() != null) {
				item.getItemProperty("start").setValue(DataHelper.formatDisplayDay.format(cartEntry.getStart()));
			}
			if (cartEntry.getEnd() != null) {
				item.getItemProperty("end").setValue(DataHelper.formatDisplayDay.format(cartEntry.getEnd()));
			}
			item.getItemProperty("attributes").setValue(cartEntry.getAttributes().toString());
			*/
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// recipient
		recipient = new Label();
		recipient.setCaption("Empfänger");
		recipient.setImmediate(false);
		recipient.setWidth("-1px");
		recipient.setHeight("-1px");
		recipient.setValue("recipient");
		mainLayout.addComponent(recipient, "top:40.0px;left:21.0px;");
		
		// cartEntries
		cartEntries = new Table();
		cartEntries.setImmediate(false);
		cartEntries.setWidth("100.0%");
		cartEntries.setHeight("100.0%");
		mainLayout.addComponent(cartEntries,
				"top:80.0px;right:20.0px;bottom:20.0px;left:20.0px;");
		
		return mainLayout;
	}

}
