package org.mgnl.nicki.vaadin.base.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class DataView extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table userTable;
	@AutoGenerated
	private Label title;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private String titleString;
	private Container container;
	private int length;
	
	private static final long serialVersionUID = -1786011895038782304L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param pnwPerson 
	 * @param actionsView 
	 */
	public DataView(Container container, String titleString, int length) {
		this.titleString = titleString;
		this.container = container;
		this.length = length;

		buildMainLayout();
		setCompositionRoot(mainLayout);

		init();
	}
	
	private void init() {
		title.setValue(titleString);
		userTable.setContainerDataSource(this.container);
		userTable.setColumnWidth("name", 200);
		userTable.setColumnWidth("value", 600);
		userTable.setPageLength(this.length);
	}
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// title
		title = new Label();
		title.setImmediate(false);
		title.setWidth("-1px");
		title.setHeight("-1px");
		title.setValue("Verantwortlichkeit aendern");
		mainLayout.addComponent(title, "top:20.0px;left:20.0px;");
		
		// userTable
		userTable = new Table();
		userTable.setImmediate(false);
		userTable.setWidth("-1px");
		userTable.setHeight("-1px");
		mainLayout.addComponent(userTable, "top:40.0px;left:20.0px;right:20.0px;");
		return mainLayout;
	}

}
