# BaseDN
nicki.users.basedn			= ou=users,o=utopia
nicki.shops.basedn			= ou=shops,o=utopia
nicki.scripts.basedn		= ou=scripts,o=utopia
nicki.mailtemplates.basedn	= ou=mailtemplates,o=utopia
nicki.projects.basedn		= ou=projects,o=utopia
nicki.templates.basedn		= ou=templates,o=utopia

nicki.roles.basedn			= cn=RoleDefs,cn=RoleConfig,cn=AppConfig,cn=UserApplication,cn=driverset,o=system
nicki.resources.basedn		= cn=ResourceDefs,cn=RoleConfig,cn=AppConfig,cn=UserApplication,cn=driverset,o=system

#nicki.login.sso				= org.mgnl.nicki.novell.userapp.jaas.UserAppAdapter
nicki.login.sso				= org.mgnl.nicki.vaadin.base.auth.DevSSOAdapter

# theme
nicki.application.theme		= reindeer

# target
nicki.targets = edir,ad

# edir

nicki.targets.edir.objects = person,project,directory,member,template,shop,shelf,article,group,role,resourceAssociation,resource,entitlement,script,org
nicki.targets.edir.objects.person 				= org.mgnl.nicki.dynamic.objects.objects.Person
nicki.targets.edir.objects.project				= org.mgnl.nicki.dynamic.objects.objects.Project
nicki.targets.edir.objects.directory			= org.mgnl.nicki.dynamic.objects.objects.Directory
nicki.targets.edir.objects.member				= org.mgnl.nicki.dynamic.objects.objects.Member
nicki.targets.edir.objects.template				= org.mgnl.nicki.dynamic.objects.objects.Template
nicki.targets.edir.objects.shop					= org.mgnl.nicki.dynamic.objects.objects.Shop
nicki.targets.edir.objects.shelf				= org.mgnl.nicki.dynamic.objects.objects.ShopShelf
nicki.targets.edir.objects.article				= org.mgnl.nicki.dynamic.objects.objects.ShopArticle
nicki.targets.edir.objects.group				= org.mgnl.nicki.dynamic.objects.objects.Group
nicki.targets.edir.objects.role					= org.mgnl.nicki.dynamic.objects.objects.Role
nicki.targets.edir.objects.resourceAssociation	= org.mgnl.nicki.dynamic.objects.objects.ResourceAssociation
nicki.targets.edir.objects.resource				= org.mgnl.nicki.dynamic.objects.objects.Resource
nicki.targets.edir.objects.entitlement			= org.mgnl.nicki.dynamic.objects.objects.Entitlement
nicki.targets.edir.objects.script				= org.mgnl.nicki.dynamic.objects.objects.Script
nicki.targets.edir.objects.org					= org.mgnl.nicki.dynamic.objects.objects.Org

nicki.targets.edir.providerUrl					= LDAP://172.17.2.91:389
nicki.targets.edir.securityAuthentication		= simple
nicki.targets.edir.securityPrincipal			= cn=admin,o=system
nicki.targets.edir.securityCredentials			= N0v3ll

# ad

nicki.targets.ad.objects = person,group,org
nicki.targets.ad.objects.person					= org.mgnl.nicki.dynamic.objects.ad.Person
nicki.targets.ad.objects.group					= org.mgnl.nicki.dynamic.objects.ad.Group
nicki.targets.ad.objects.org					= org.mgnl.nicki.dynamic.objects.ad.Org

nicki.targets.ad.providerUrl					= LDAP://172.17.2.93:389
nicki.targets.ad.securityAuthentication			= simple
nicki.targets.ad.securityPrincipal				= CN=Administrator,CN=Users,DC=ad,DC=ism,DC=utopia,DC=novell,DC=com
nicki.targets.ad.securityCredentials			= n0v3ll


# Person Search
nicki.editor.person.basedn = ou=users,o=utopia

# i18n
nicki.core.i18n.base = i18n.messages




