package org.mgnl.nicki.shop.core;

import org.mgnl.nicki.dynamic.objects.shop.Cart;
import org.mgnl.nicki.dynamic.objects.shop.CartEntry;
import org.mgnl.nicki.dynamic.objects.shop.Catalog;
import org.mgnl.nicki.dynamic.objects.shop.CatalogArticle;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class CartViewer extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table cartEntries;
	@AutoGenerated
	private Label recipient;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	private static final long serialVersionUID = 8441664095916322794L;
	private Cart cart;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CartViewer(Cart cart) {
		this.cart = cart;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.recipient.setValue(this.cart.getRecipient().getDisplayName());
		fillCartEntries();
	}

	private void fillCartEntries() {

		cartEntries.addContainerProperty("action", String.class, "");
		cartEntries.setColumnWidth("action", 50);
		cartEntries.setColumnHeader("action", "action");
		cartEntries.addContainerProperty("right", String.class, "");
		cartEntries.setColumnWidth("right", 420);
		cartEntries.setColumnHeader("right", "id");
		cartEntries.addContainerProperty("attributes", String.class, "");
		cartEntries.setColumnWidth("attributes", 420);
		cartEntries.setColumnHeader("attributes", "attributes");
		for (String entryId : cart.getCartEntries().keySet()) {
			CartEntry cartEntry = cart.getCartEntry(entryId);
			Item item = cartEntries.addItem(cartEntry);
			CatalogArticle article = Catalog.getCatalog().getArticle(entryId);
			item.getItemProperty("right").setValue(article.getDisplayName());
			item.getItemProperty("action").setValue(cartEntry.getAction());
			item.getItemProperty("attributes").setValue(cartEntry.getAttributes());
			item.getItemProperty("dateTo").setValue(cartEntry.getEnd());
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// recipient
		recipient = new Label();
		recipient.setCaption("Empfänger");
		recipient.setImmediate(false);
		recipient.setWidth("-1px");
		recipient.setHeight("-1px");
		recipient.setValue("recipient");
		mainLayout.addComponent(recipient, "top:40.0px;left:21.0px;");
		
		// cartEntries
		cartEntries = new Table();
		cartEntries.setImmediate(false);
		cartEntries.setWidth("100.0%");
		cartEntries.setHeight("100.0%");
		mainLayout.addComponent(cartEntries,
				"top:80.0px;right:20.0px;bottom:20.0px;left:20.0px;");
		
		return mainLayout;
	}

}
