package org.mgnl.nicki.vaadin.base.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class SimpleEditor extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout;
	@AutoGenerated
	private TextArea editor;
	private Property data;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SimpleEditor(Property dataContainer) {
		this.data = dataContainer;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		editor.setValue(data.getValue());
		editor.addListener(new Property.ValueChangeListener() {
			
			public void valueChange(ValueChangeEvent event) {
				data.setValue((String) editor.getValue());
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout
		verticalLayout = buildVerticalLayout();
		mainLayout.addComponent(verticalLayout,
				"top:20.0px;right:20.0px;bottom:20.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout() {
		// common part: create layout
		verticalLayout = new VerticalLayout();
		verticalLayout.setWidth("100.0%");
		verticalLayout.setHeight("100.0%");
		verticalLayout.setImmediate(false);
		verticalLayout.setMargin(false);
		
		// editor
		editor = new TextArea();
		editor.setWidth("100.0%");
		editor.setHeight("100.0%");
		editor.setImmediate(true);
		verticalLayout.addComponent(editor);
		
		return verticalLayout;
	}

}
