/**
 * This file Copyright (c) 2003-2011 Dr. Ralf Hirning
 * All rights reserved.
 *
 *
 * This file is dual-licensed under both the GNU General
 * Public License and an individual license with Dr. Ralf
 * Hirning.
 *
 * This file is distributed in the hope that it will be
 * useful, but AS-IS and WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE, TITLE, or NONINFRINGEMENT.
 * Redistribution, except as permitted by whichever of the GPL
 * or the individual license, is prohibited.
 *
 * 1. For the GPL license (GPL), you can redistribute and/or
 * modify this file under the terms of the GNU General
 * Public License, Version 3, as published by the Free Software
 * Foundation.  You should have received a copy of the GNU
 * General Public License, Version 3 along with this program;
 * if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * 2. For the individual license, this file and the accompanying
 * materials are made available under the terms of the
 * individual license.
 *
 * Any modifications to this file must keep this entire header
 * intact.
 *
 */
package org.mgnl.nicki.vaadin.base.components;

import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.vaadin.base.application.NickiApplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button.ClickEvent;

@SuppressWarnings("serial")
public class WelcomeDialog extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Button logout;
	@AutoGenerated
	private Label space;
	@AutoGenerated
	private Label hello;
	
	private NickiApplication application;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public WelcomeDialog(NickiApplication app) {
		this.application = app;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		hello.setValue(I18n.getText("nicki.application.greeting", application.getNickiContext().getUser().getDisplayName()));
		logout.setCaption(I18n.getText("nicki.application.logout"));
		logout.addClickListener(new Button.ClickListener() {
			
			public void buttonClick(ClickEvent event) {
				application.logout();
			}
		});

	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		//horizontalLayout_1.setWidth("1000px");
		//horizontalLayout_1.setHeight("100px");
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		
		// hello
		hello = new Label();
		hello.setWidth("-1px");
		hello.setHeight("-1px");
		hello.setValue("Hello");
		hello.setImmediate(false);
		mainLayout.addComponent(hello);
		mainLayout.setComponentAlignment(hello, new Alignment(33));
		
		// space
		space = new Label();
		space.setWidth("10px");
		space.setHeight("-1px");
		space.setImmediate(false);
		mainLayout.addComponent(space);
		
		// logout
		logout = new Button();
		logout.setWidth("-1px");
		logout.setHeight("-1px");
		logout.setImmediate(false);
		mainLayout.addComponent(logout);
		
		return mainLayout;
	}

}
