package org.mgnl.nicki.vaadin.base.components;

import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.vaadin.base.application.NickiApplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button.ClickEvent;

@SuppressWarnings("serial")
public class WelcomeDialog extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button logout;
	@AutoGenerated
	private Label space;
	@AutoGenerated
	private Label hello;
	
	private NickiApplication application;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public WelcomeDialog(NickiApplication app) {
		this.application = app;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		hello.setValue(I18n.getText("nicki.application.greeting", application.getNickiContext().getUser().getName()));
		logout.setCaption(I18n.getText("nicki.application.logout"));
		logout.addListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				application.logout();
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setMargin(false);
		
		// hello
		hello = new Label();
		hello.setWidth("-1px");
		hello.setHeight("-1px");
		hello.setValue("Hello");
		hello.setImmediate(false);
		horizontalLayout_1.addComponent(hello);
		horizontalLayout_1.setComponentAlignment(hello, new Alignment(33));
		
		// space
		space = new Label();
		space.setWidth("10px");
		space.setHeight("-1px");
		space.setImmediate(false);
		horizontalLayout_1.addComponent(space);
		
		// logout
		logout = new Button();
		logout.setWidth("-1px");
		logout.setHeight("-1px");
		logout.setImmediate(false);
		horizontalLayout_1.addComponent(logout);
		
		return horizontalLayout_1;
	}

}
